### PR TITLE
fix(BolusExtraCommand): Fixes squareWaveExtendedTime

### PR DESCRIPTION
**Pull request by bastiaanv**
I was looking through the code and saw that the `squareWaveDuration` variable uses the same `encodedData` bytes as `timeBetweenPulses` in the `init` function while it doesn't do this in the `data` function.

I am not completely sure if the change is incorrect and the `data` function should be changed

### CODE REVIEW

**Comment by ps2** [comment]
I think this may be correct, thanks. Could you add a test for this? It would help verify that the encoding and decoding match.

**Comment by bastiaanv** [comment]
During the make of the test, I found something else: there was a difference factor of 10 between encoding and decoding. After some testing, I think it is wrong on the encoding side, but @ps2 can you check that just to be sure?

**Comment by itsmojo** [comment]
Besides the mistake in the BolusExtraCommand intervalCounts calculation, there are a number of issues with the new tests. Having an encode test for a 2.6U immediate bolus with 1 second pulses with a 36U extended bolus over 1 hour is not a "typical  prime" as a prime bolus cannot be combined with anything and 30U is the maximum supported bolus size. Also, it would be good to make sure that the BolusExtraCommand handles extended boluses without an immediate bolus portion.  I think that the BolusExtraCommand encode function should be able to take a timeBetweenPulses of 0 when there is no immediate bolus. Supporting this requires the following one line change to OmnipodCommon/MessageBlocks/BolusExtraCommand.swift (since for non prime boluses I believe that the pod insists that the minimum time between pulses is 2 seconds -- even when there are no pulses).

Old line 73:     self.timeBetweenPulses = timeBetweenPulses
New line 73:   self.timeBetweenPulses = timeBetweenPulses > 0 ? timeBetweenPulses : .seconds(2)

Here's a my corrected and updated BolusTests (assuming the above one line change for the no immediate bolus extended boluses). These samples were all taken from real life examples captured in the openomni wiki and described in https://github.com/openaps/openomni/wiki/Command-17-Bolus-extra.

    func testBolusExtraSquareWave() {
        // 6.0U combo bolus with 2.0U immediate and 4.0U over 3 hours
        // 17 0d 3c 0190 00030d40 0320 00cdfe60
        do {
            let cmd = try BolusExtraCommand(encodedData: Data(hexadecimalString: "170d3c019000030d40032000cdfe60")!)            
            XCTAssertEqual(2.0, cmd.units)
            XCTAssertEqual(false, cmd.acknowledgementBeep)
            XCTAssertEqual(false, cmd.completionBeep)
            XCTAssertEqual(.hours(1), cmd.programReminderInterval)
            XCTAssertEqual(.seconds(2), cmd.timeBetweenPulses)
            XCTAssertEqual(4, cmd.squareWaveUnits)
            XCTAssertEqual(.hours(3), cmd.squareWaveDuration)
        } catch (let error) {
            XCTFail("message decoding threw error: \(error)")
        }

       // Encode 0.1 combo Bolus with 0.05U immediate, 0.05U over 30 minutes
        let cmd = BolusExtraCommand(units: 0.05, timeBetweenPulses: .seconds(2), squareWaveUnits: 0.05, squareWaveDuration: .hours(0.5), programReminderInterval: .minutes(60))
        XCTAssertEqual("170d3c000a00030d40000a0aba9500", cmd.data.hexadecimalString)
    }

    func testExtendedBolusNoImmediate() {
       // 1.0U extended bolus over 1 hour with nothing immediate
       // 17 0d 7c 0000 00030d40 00c8 0112a880
       do {
            let cmd = try BolusExtraCommand(encodedData: Data(hexadecimalString: "170d7c000000030d4000c80112a880")!)             
            XCTAssertEqual(false, cmd.acknowledgementBeep)
            XCTAssertEqual(true, cmd.completionBeep)
            XCTAssertEqual(.minutes(60), cmd.programReminderInterval)
            XCTAssertEqual(0.0, cmd.units)
            XCTAssertEqual(.seconds(2), cmd.timeBetweenPulses)
            XCTAssertEqual(1.0, cmd.squareWaveUnits)
            XCTAssertEqual(.hours(1), cmd.squareWaveDuration)
        } catch (let error) {
            XCTFail("message decoding threw error: \(error)")
        }

        // Encode 1.0U extended bolus over 4.5 hours with nothing immediate
        let cmd = BolusExtraCommand(units: 0.0, timeBetweenPulses: 0, squareWaveUnits: 1.0, squareWaveDuration: .hours(4.5))
        XCTAssertEqual("170d00000000030d4000c804d3f640", cmd.data.hexadecimalString)
    }
  
Is is *very important* to make the identical changes to rileylink repo in the OmniKit/OmnipodCommon/MessageBlocks/BolusExtraCommands.swift and to OmniKitTests/BolusTests.swift files!

**Comment by bastiaanv** [comment]
@itsmojo Sorry for the last commit, but I applied your feedback in the lastest commit

**Comment by ps2** [comment]
Square wave fixes addressed in this PR: https://github.com/LoopKit/OmniBLE/pull/69

**Pull request closed without merging**
