### PR TITLE
Various BlueTooth and MessageBlocks fixes & updates

### PR DESCRIPTION
**Pull request by itsmojo**
+ Two Bluetooth fixes needed to handle payloads > 255 bytes
+ Correct PodInfoActivationTime & PodInfoTriggeredAlerts defs
+ Rename PodInfoConfiguredAlerts to PodInfoTriggeredAlerts
+ Update PodInfoTriggeredAlerts to be only time based triggers
+ Update PodInfoPulseLog & PodInfoPulseLogPlus output
+ Have ConfigureAlertsCommand enforce the max alert duration value
+ Update TimeIntervalStr to only include minutes when non-zero
+ Update all PodInfoTests to compile, cleanly run & make sense

### CODE REVIEW

**Comment by marionbarker** [comment]
Testing this with Loop-dev and I am not getting the Loop alerts expected from low reservoir --> testing error. Ignore this comment.

Test details:
* start with dev branch (of LoopWorkspace) and apply OmniBLE patches for 102, 106, 108 and 109 PRs.
* Builds and tests nominally when issuing commands including deactivate, pair and insert, suspend, resume, manual TB
* use the rPi front end to adjust reservoir levels and minutes since activation

At this point - operator error. see later comment where this was tested correctly.
* ~~expect to get Loop alerts and I do not get them - I do see the level reported by Loop and the time until expiration update, but not getting notified by Loop~~
* ~~would like someone to confirm this~~

**Comment by marionbarker** [comment]
Make sure this works without these changes. Restore to dev version with no modifications to OmniBLE.
I'm not getting notifications from Loop for this case either. So maybe it is my set-up.

I was confused about testing with the rPi.
(See next comment - I need to set alert level with front end.)

Results before applying PR 109:
* set alert to LowReservoir(4) with rPi front end
   * Loop modal alert displays low value
   * acknowledge modal alert on Loop
   * active alert on rPi is cleared
* set alert to ExpirationReminder(3) with rPi front end
   * Loop modal alert displays pod expires in 19 hours
   * acknowledge modal alert on Loop
   * active alert on rPi is cleared

**Comment by itsmojo** [comment]
The rpi sim is pretty basic and doesn't currently have any code to actual implement the alerts based on time or reservoir level as configured by a controlling app. To use rpi for testing things like this, you'd have to manually force the pod alerts (probably should do this after manually adjusting the pod time or the reservoir level to make sense) to get Loop to notice.

**Comment by itsmojo** [comment]
PR https://github.com/LoopKit/pod/pull/11 is needed for a pod sim with support for all of these pod info types (including the needed Bluetooth fixes needed for the larger messages as in a type 3 pod info request), but there is currently no pump manager or UI support in Loop to be able to exercise most of these pod info requests right now. The only available testing that can currently be done with Loop would be the updated unit tests contained in this PR.

This code can also be tested indirectly in either freeaps_dev or iAPS dev which should have the exact same MessageBlocks files and other fixes as in this PR but with pod diagnostics in the UI that can be used to manually exercise all the new pod info requests with rpi pod simulator running with the above mentioned PR or a live pod.

**Comment by marionbarker** [comment]
Redid the testing for this PR, as far as is possible with Loop.

The alerts were all tested with the version of the pod simulator that includes PR https://github.com/LoopKit/pod/pull/11

As stated before, all the nominal DASH commands worked as expected (went through every option and ran with autobolus and a glucose pattern for a while).
This comment just covers alerts.

Procedure:
1. Set the alert on the rPi DASH front end
2. On Loop phone, tap the sound icon to get status
3. Report the Loop provided modal alert

Test Results:
* ShutdownImminent(2): "Pod expired, delivery will stop in 1 hour" (regardless of actual minutes since activation
* ExpirationReminder(3): "Pod expires in XX hours" where XX varies depending on minutes since activation
* LowReservoir(4): "Low reservoir. XX U or less remaining in Pod" where XX is the value set in notifications regardless of reservoir level
* SuspendedReminder(5): not getting a modal alert like with the other (pod-only alert so rPi won't support this)
* SuspendedExpired(6): "Resume Insulin, The insulin suspension period has ended . . ." regardless of whether insulin is suspended or not
* Lifecycle(7): "Pod Expired, change pod now. Pod has been active for 72 hours" regardless of actual minutes since activation

Note: the slots 0 and 1 are labeled AutoOff and Unused. Like SuspendedReminder, they are not used for a modal alert.

**Comment by itsmojo** [comment]
This all looks like what I would expect with the current limited functionality of the rpi pod simulator. Note that the SuspendedReminder(5) pod alert is not any different from any other alert with the rpi pod sim. It's Loop that ignores alert #5 and the pod alert is simply acknowledged without any user intervention with a modal alert for the on going suspend.  Thus the user will only get one suspend reminder beep after 15m and then no others for suspends longer than 30m.

**Comment by marionbarker** [comment]
In addition to the rPi DASH testing listed above, I ran the tests and all were successful (after first applying the iOS 17 updates from Loop PR 2080 and LoopKit PR 517).

**Comment by marionbarker** [comment]
This PR has been added to all the other open OmniBLE PR.
Code continues to run nominally.

**Comment by marionbarker** [comment]
Code review of last commit:
* No effect on Loop Operation

Test latest version:
* works as expected on test phone (using rPi DASH simulator: went through deactivate, new pod setup and closed-loop operations)
* works as expected on real phone using an actual DASH pod (continued using with an in-process pod)

Added information from PM by author for historical record:

"
. . . define for the DASH type 7 pod info request  . . .  returns a standard status response (as type 0 does) but without incrementing the message sequence #. This pod info request is used by the DASH PDM for most of its get status requests except in a few particular situations.

. . .  by adding this simple update to PodInfo.swift . . . OmniBLEParser will be able to fully parse pod sim output when used with a DASH PDM
"

**Pull request merged**
