### PR TITLE
handle formats from app logs and Xcode logs for Loop, Trio, iAPS

### PR DESCRIPTION
**Pull request by marionbarker**
The parser embedded in the OmniBLE module can parse information found in the log files from several apps that use it as well as from the Xcode logs when those apps are connected to a Mac.

### Successful test with:
* Loop: Loop Report
* Trio: log.txt and log_prev.txt
* older iAPS / FAX from 2022: log_prev.txt
* Loop: Xcode debug file
* Trio: Xcode debug file

### CODE REVIEW

**Comment by marionbarker** [comment]
In order to test the parser, follow these steps:

Start Xcode in the workspace folder:
1. Click on Scheme in Xcode:
2. Select OmniBLE Parser
3. Select Edit Scheme (see graphics below - Trio example, same method used for LoopWorkspace)
   * If an argument exists, edit it
   * If not, add an argument to the "Arguments Passed on Launch" section
   * Insert the full path name to the file to process (embed the path in quotes if there are spaces in the path name)
4. Click on Run and the output in the debug log is the parsed file.

omnible-parser-screenshot-01 
omnible-parser-screenshot-02



For example, I added an argument and inserted /Users/marion/Downloads/log_prev.txt on the line.

**Review by bjornoleh — APPROVED** [review]
Tested successfully with an older iAPS log file, and a recent Trio dev log file.

Please note that the parsing failed when I tested with a file that was automatically renamed to `log (1).txt`upon download due to the presence of another `log.txt` file in the Downloads dirctory. 

When moving and renaming the same file to `log.txt` in another directory, the parsing succeeded. I expect the whitespace in the file name to have been the issue (confirmed by renaming the file to `log .txt`, which also failed). This is not a dealbreaker, but I'lll mention it for completeness as this was due to an automated rename.

**Comment by marionbarker** [comment]
Thank you for testing. 

The instructions in my comment did include a bullet “(embed the path in quotes if there are spaces in the path name)”. 

I thought arguments might need to allow spaces as delimiters if the arguments used flags. If that is true, then the quotes are required. But I’m not confident on this. Perhaps @itsmojo has a comment. It would be more convenient if the user didn’t need to check for spaces.

**Comment by bjornoleh** [comment]
Ok, sorry, I must confess I did not read the instructions that thoroughly since I had recently used the parser and was familiar with the steps. 

I tested with quotes around the path of the filename with spaces, and that did indeed work.

**Comment by itsmojo** [comment]
OmniBLEParser (and its cousin OmniKitPacketParser) have always parsed its arguments using the built-in [CommandLine](https://developer.apple.com/documentation/swift/commandline) which treats a space as an argument delimiter unless it's quoted or escaped as one would expect (just like invoking a Unix C command line program). A possible future enhancement might be to add shell-like special character file handling (e.g., globbing,  tilda support etc.) for OmniBLEParser's arguments when it is run within Xcode, but since this is an extremely specialized command line tool for developers looking at Omnipod logs, it's probably not worth thinking about this at this time and you'd probably still have the same issues with space handling in file names.

**Comment by bjornoleh** [comment]
Thanks! Yes, this is all good, and certainly not a blocker for merging this PR, as it’s both unrelated to the PR and manageable for the target audience as you say.

**Pull request merged**
