### PR TITLE
Fix of disabling iPhone auto-lock during pod pairing

### PR DESCRIPTION
**Pull request by dnzxy**
This PR attempts to fix issues found through testing by @marionbarker in PR #100 as that PR has already been merged due to an oversight on my part and by @ps2.

### CODE REVIEW

**Comment by marionbarker** [comment]
I will be posting testing comments here soon.

**Comment by marionbarker** [comment]
This comment summarizes testing results and explains why the code was restored to an older version. 

I will repeat the testing (from PR 100) and report the results in a later comment.

### Summary:

The first commit for the original PR #100 worked robustly and was tested extensively. [Testing for commit 26e4125](https://github.com/LoopKit/OmniBLE/pull/100#issuecomment-1771808673)

Some changes to the code were requested, but the way in which those changes were implemented introduced behavior that is reproducible but is not the behavior we want. (Reference commit f9a7ba7 merged into dev as PR 100).

We tried several things but could not prevent the undesirable behavior.

In order to robustly add the disable auto-lock for the selected screens, we have returned to the original method (as was used for 26e4125). If someone can suggest a change to the non-working hostingController, I'm willing to test it.

### Undesirable Behavior

The signature of the not-working code (several different versions tried)

* for first call to hostingController requesting the idle timer to be disabled, the screens are displayed with the idle timer disabled as desired and expected
* subsequent calls to hostingController requesting the idle timer to be disabled, the screens do not have the idle timer disabled

However, with the non-working code, if you alternate calls to the hostingController with requests to set the idle timer to be disabled with one or more intervening calls which do not, then the screens lock as expected. In other words:

If request to disable idle timer is included in the call to hostingController for a given case:
* n: .deactivate
* y: .pairPod
* n: .confirmAttachment
* y: .insertCannula
* n: .checkInsertedCannula
* y: .setupComplete

Works as expected. But since we do not understand this behavior, this is not an acceptable solution.

### Details about the code changes:

Original code with no disable of auto-lock:

```
function call:
            let view = hostingController(rootView: InsertCannulaView(viewModel: viewModel))

function:
    private func hostingController<Content: View>(rootView: Content) -> DismissibleHostingController<some View> {
        return DismissibleHostingController(content: rootView, colorPalette: colorPalette)
    }
```

Code that works to disable auto-lock on each instance it is applied:

```
function call:
            let view = hostingController(rootView: InsertCannulaView(viewModel: viewModel).onAppear(perform: {UIApplication.shared.isIdleTimerDisabled = true}), onDisappear: {UIApplication.shared.isIdleTimerDisabled = false})

function:
    private func hostingController<Content: View>(rootView: Content, onDisappear: @escaping () -> Void = {}) -> DismissibleHostingController<some View> {
        return DismissibleHostingController(content: rootView, onDisappear: onDisappear, colorPalette: colorPalette)
    }
```

Code with problem described in Undesirable Behavior, above.

```
function call:
    let view = hostingController(rootView: InsertCannulaView(viewModel: viewModel), isIdleTimerDisabled: true)

function:
    private func hostingController<Content: View>(rootView: Content, isIdleTimerDisabled: Bool = false) -> DismissibleHostingController<some View> {
        let rootViewWithAppearance = rootView.onAppear {
            if isIdleTimerDisabled {
                UIApplication.shared.isIdleTimerDisabled = true
            }
        }
        .onDisappear {
            if isIdleTimerDisabled {
                UIApplication.shared.isIdleTimerDisabled = false
            }
        }
        
        return DismissibleHostingController(content: rootViewWithAppearance, colorPalette: colorPalette)
    }
```

**Comment by gestrich** [comment]
@marionbarker @dnzxy A few observations that may be helpful:

This may be known but I wanted to point out that the code that doesn't work uses a different "disappear" method than the one that works. This code:

```
let view = hostingController(rootView: InsertCannulaView(viewModel: viewModel).onAppear(perform: {UIApplication.shared.isIdleTimerDisabled = true}), onDisappear: {UIApplication.shared.isIdleTimerDisabled = false})

```

That `onDisappear` is a parameter of `DismissibleHostingController`, a UIHostingController. That block is used in the `viewDidDisappear` method documented [here](https://github.com/LoopKit/LoopKit/blob/dev/LoopKitUI/View%20Controllers/DismissibleHostingController.swift#L113).

In contrast, the broken code is using the `.onDisappear` view function. That method is part of SwiftUI as documented [here](https://developer.apple.com/documentation/swiftui/view/ondisappear(perform:)).

I think you are seeing differences in the way UIKit vs SwiftUI calls their respective disappear methods.  

A good way to debug this is to add some print statements in the SwiftUI onAppear/onDisappear methods. I did so for the first 2 views. Then I navigated to the PodSetupView then the ExpirationReminderSetupView

```
PodSetupView: onAppear called
ExpirationReminderSetupView: onAppear called
PodSetupView: onDisappear called
```

Note that PodSetupView's onDisappear is called _after_ ExpirationReminderSetupView's `onAppear`. I think that ordering is unexpected for the work you are doing and would essentially undo what happened in the onAppear of ExpirationReminderSetupView.

That's not an answer for how to fix but that is my quick review of what the problem may be.

**Comment by marionbarker** [comment]
Thanks Bill (@gestrich).  Your print-out makes it very clear why we were getting the behavior that I consistently saw when testing. Successive calls would undo the idle timer disable (after the first one). But alternating calls does work.

**Comment by marionbarker** [comment]
To clarify, this PR returns OmniBLE implementation of disable auto-lock to the version of commit 26e4125.
This has been tested and matches the final result already merged into OmniKit: https://github.com/LoopKit/OmniKit/pull/22.

**Pull request merged**
